version: '4.1'
services:
  app:
    container_name: qorakoli_db
    image: qorakoli_db
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - qorakoli_db
  dbpostgresql:
    image: qorakoli_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: qorakoli_db
      POSTGRES_DB: qorakoli_db