version: '4.1'
services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - "2222:5432"
    environment:
      POSTGRES_DB: qorakoli_db
      POSTGRES_USER: qorakoli_db
      POSTGRES_PASSWORD: 12345
    volumes:
      - pg13data:/var/lib/postgresql/data
    networks:
      app-network:
  postgrs_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      app-network:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    environment:
      DB_SERVER: db
      POSTGRE_DB: qorakoli_db
      POSTGRES_USER: qorakoli_db
      POSTGRES_PASSWORD: 12345
      PG_URL: jdbc:postgresql://192.168.1.170:2222/qorakoli_db
    ports:
      - "8080:8080"
    networks:
      app-network:


networks:
  app-network:
    driver: bridge

volumes:
  db:
  pg13data:
  app:
  postgrs_admin:

