version: '4.1'
services:
  app:
    container_name: qorakol
    image: qorakol
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: qorakol
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: qorakoli_db
      POSTGRES_DB: qorakoli_db